version: "3"

services:
  media_service_tcp_server:
    image: media_service_tcp_server
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    volumes:
      - multimedia:/media/samba/multimedia/
    build:
      context: .
      dockerfile: Dockerfile.tcp_server
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}

    ports:
      - 8000:8000

  linux_services:
    image: media_service_linux_services
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    volumes:
      - transmission:/media/samba/transmission/
    build: 
      context: .
      dockerfile: Dockerfile.linux_services
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}

    ports:
      - 51413:51413
      - 51413:51413/udp 
      - 8001:8001


volumes:
  multimedia:
    name: multimedia
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},iocharset=utf8,sec=ntlmssp,file_mode=0777,dir_mode=0777"
      device: "//${samba_address}/share/multimedia/"
  transmission:
    name: transmission
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},iocharset=utf8,sec=ntlmssp,file_mode=0777,dir_mode=0777"
      device: "//${samba_address}/share/transmission/"
