FROM debian:12

USER root

ARG samba_user
ARG samba_password
ARG samba_domain

RUN apt update && apt upgrade -y &&\
    apt install git npm python3-pip -y

RUN mkdir settings &&\
    mkdir /media/samba &&\
    mkdir /media/samba/multimedia

WORKDIR /app

COPY ./src/ /app/src/
COPY ./configs/for_docker/media_service_config.ini /app/src/main/python/config/config.ini
COPY ./configs/for_docker/parsers_config.ini /app/src/main/python/multi_parser/src/config.ini

RUN git clone https://github.com/Ferlony/multi_parser.git /multi_parser &&\
    mv /multi_parser/ /app/src/main/python/multi_parser

# RUN mkdir /app/src/main/resources/mediaservice/src/templates/js/node_modules/

RUN rm /usr/lib/python3.*/EXTERNALLY-MANAGED

RUN pip install -r src/main/python/requirements.txt &&\
	pip install -r src/main/python/multi_parser/requirements.txt

RUN python3 -m src.main.python.db.user_worker_db --option 1

WORKDIR /app/src/main/resources/mediaservice/src/templates/js/node_modules
RUN npm i shaka-player

WORKDIR /app

EXPOSE 8000 

CMD ["python3", "-m", "src.main.python.main_MediaService"]
