FROM debian:12

USER root

ARG samba_user
ARG samba_password
ARG samba_domain

RUN apt update && apt upgrade -y &&\
    apt install transmission-daemon -y

RUN mkdir settings &&\
    mkdir /media/samba &&\
    mkdir /media/samba/transmission

COPY ./configs/for_docker/settings.json /etc/transmission-daemon/settings.json

EXPOSE 51413/tcp 51413/udp 8001

CMD ["systemctl", "start", "transmission-daemon.service"]
