version: "3"

services:
  media_service_tcp_server:
    image: media_service_tcp_server
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    volumes:
      - multimedia:/media/samba/multimedia/
    build:
      context: .
      dockerfile: Dockerfile.tcp_server
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}
        samba_address: ${samba_address}

    ports:
      - 8000:8000

  transmission_daemon:
    image: transmission_daemon
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    volumes:
      - transmission:/media/samba/transmission/
    build: 
      context: .
      dockerfile: Dockerfile.transmission_daemon
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}
        samba_address: ${samba_address}

    ports:
      - 51413:51413
      - 51413:51413/udp 
      - 8001:8001
    
  postgres:
    image: postgres:13.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"


volumes:
  multimedia:
    name: multimedia
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},file_mode=0777,dir_mode=0777"
      device: "//${samba_address}/multimedia/"
  transmission:
    name: transmission
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},file_mode=0777,dir_mode=0777"
      device: "//${samba_address}/transmission/"
  pgdata:
    name: pgdata_mediaservice
