version: "3"

services:
  samba_storage:
    image: samba_storage
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    volumes:
      - multimedia:/share/transmission/
      - transmission:/share/multimedia/
    build:
      context: .
      dockerfile: Dockerfile.samba_storage
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}
        host_ip: ${host_ip}
    ports:
      - 8010:445
      # - 8011:137
      # - 8012:138
      # - 8013:139

  media_service_tcp_server:
    image: media_service_tcp_server
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    depends_on:
      - samba_storage
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - multimedia:/media/samba/multimedia/
    build:
      context: .
      dockerfile: Dockerfile.tcp_server
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}
        host_ip: ${host_ip}

    ports:
      - 8000:8000

  linux_services:
    image: media_service_linux_services
    environment:
      - TZ="Europe/Dublin"
    env_file: 
      - .env
    depends_on:
      - samba_storage
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    volumes:
      - transmission:/media/samba/transmission/
    build: 
      context: .
      dockerfile: Dockerfile.linux_services
      args:
        samba_user: ${username}
        samba_password: ${password}
        samba_domain: ${domain}
        host_ip: ${host_ip}

    ports:
      - 51413:51413
      - 51413:51413/udp 
      - 8001:8001


volumes:
  multimedia:
    name: multimedia
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},port=8010,iocharset=utf8,sec=ntlmssp,vers=3.0,file_mode=0777,dir_mode=0777"
      device: "//${host_ip}/share/multimedia/"
  transmission:
    name: transmission
    driver_opts:
      type: cifs
      o: "username=${username},password=${password},port=8010,iocharset=utf8,sec=ntlmssp,vers=3.0,file_mode=0777,dir_mode=0777"
      device: "//${host_ip}/share/transmission/"
