version: "3"

services:
  postgres:
     image: postgres:13.3
     volumes:
       - pgdata:/var/lib/postgresql/data
     env_file: 
       - .env
     environment:
       POSTGRES_DB: "postgres"
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     healthcheck:
       test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
       interval: 30s
       timeout: 60s
       retries: 5
       start_period: 80s
     ports:
       - "5432:5432"
 
volumes:
  pgdata:
    name: pgdata_mediaservice

