version: "3"

services:
  samba_storage:
    image: samba_storage
    environment:
      - TZ="Europe/Dublin"
    build:
      context: .
      dockerfile: Dockerfile.samba_storage
    ports:
      - 8003:445
  media_service_tcp_server:
    image: media_service_tcp_server
    environment:
      - TZ="Europe/Dublin"
    depends_on:
      - samba_storage
    build:
      context: .
      dockerfile: Dockerfile.tcp_server
    ports:
      - 8000:8000
  linux_services:
    image: media_service_linux_services
    environment:
      - TZ="Europe/Dublin"
    depends_on:
      - samba_storage
    build: 
      context: .
      dockerfile: Dockerfile.linux_services
    ports:
      - 51413:51413
      - 51413:51413/udp 
      - 8001:8001
