version: "3"

services:
  samba_storage:
    image: samba_storage
    build:
      context: .
      dockerfile: Dockerfile.samba_storage
      ports:
        - 445:8003

  media_service_tcp_server:
    image: media_service_tcp_server
    depends_on:
      - samba_storage
    build:
      context: .
      dockerfile: Dockerfile.tcp_server
      ports:
        - 8000:8000

  linux_services:
    image: media_service_linux_services
    depends_on:
      - samba_storage
    build: 
      context: .
      dockerfile: Dockerfile.linux_services
      ports:
        - 51413/tcp:51413/tcp
        - 51413/udp:51413/udp 
        - 8001:8001
